### PR TITLE
Fixed zero-tick delta behavior (#41)

### LINKED ISSUE #41: Update the logic in StepTimer to account for scenarios where _frequency > TicksPerSecond
As called out on https://github.com/novelrt/NovelRT/pull/34#discussion_r323548711, the StepTimer can technically bug out if the hardware timer frequency is greater than the TicksPerSecond.

This is problematic because the math is using integer arithmetic and follows `(counterDelta * TicksPerSecond) / _frequency`, so if `_frequency > TicksPerSecond` you can end up getting "zero" as the tick delta.

A solution should be devised that takes this into account so that users still get the appropriate updates.

### PR DESCRIPTION
**Pull request by Pheubel**
Handled the edge case depicted in ["Update the logic in StepTimer to account for scenarios where _frequency > TicksPerSecond"](https://github.com/novelrt/NovelRT/issues/41).

I would like a review on the implementation.

EDIT: Resolves #41 - Ruby

### CODE REVIEW

File: src/NovelRT/Timing/StepTimer.cpp [hunk 1]
```diff
@@ -8,7 +8,7 @@
 namespace NovelRT::Timing {
   StepTimer::StepTimer(uint32_t targetFrameRate, double maxSecondDelta) :
     _frequency(glfwGetTimerFrequency()),
-    _maxCounterDelta((uint64_t)(_frequency * maxSecondDelta)),
+    _maxCounterDelta((uint64_t)(_frequency* maxSecondDelta)),
```
Comment (tannergooding) [inline src/NovelRT/Timing/StepTimer.cpp]: nit: a whitespace was removed

File: src/NovelRT/Timing/StepTimer.cpp [hunk 2]
```diff
@@ -77,7 +77,8 @@ namespace NovelRT::Timing {
           subscriber(secondsDelta);
         }
       }
-    } else {
+    }
+    else {
```
Comment (tannergooding) [inline src/NovelRT/Timing/StepTimer.cpp]: @RubyNova, most K&R variants want the `else` on the same line as the closing brace, yeah?

Comment (RubyNova) [reply src/NovelRT/Timing/StepTimer.cpp]: I *believe* so, however our clang format isn't set up yet so we just kind of have both everywhere at the moment.

We should uh...probably fix that....lmao.

Comment (tannergooding) [reply src/NovelRT/Timing/StepTimer.cpp]: Well decide which we want so I know if this comment is valid :P

Comment (RubyNova) [reply src/NovelRT/Timing/StepTimer.cpp]: I think I would prefer it to be on the same line, just because doing K&R with it on a new line just looks strange.

File: src/NovelRT/Timing/StepTimer.cpp (hunk 1 above)
Comment (Pheubel) [reply src/NovelRT/Timing/StepTimer.cpp]: i don't get why VS's autoformat wants it connected.

**Comment by tannergooding** [comment]
Thanks for the fix @Pheubel
